#!/usr/bin/python3
import os
import sys

pyfile = os.environ.get('PYFILE')

if pyfile is None or pyfile == '':
    sys.exit("Error: PYFILE environment variable is not set.")

output_file = pyfile + 'c'

print(f"Compiling {pyfile} ...")
os.system(f"python3 -m py_compile {pyfile}")

# Remove the leading '__pycache__/' from the source file path
source_file = pyfile.split('/')[-1]
os.rename(f'__pycache__/{source_file}c', output_file)
os.rmdir('__pycache__')
